import React, { useState } from "react";
import Head from "next/head";
import useSWR from "swr";
import Image from "next/image";
import fetcher from "../lib/fetcher";
import { Row, Col, Button, FormControl } from "react-bootstrap";

export default function Home() {
  const { data, error, isLoading } = useSWR("/api/stats/artists", fetcher);
  const [songsToAdd, setSongsToAdd] = useState("");

  if (error) return <div>failed to load</div>;
  if (isLoading) return <div>loading...</div>;

  function addToPlaylist(songs) {
    const songId = songs.split("/", 10)[4].split("?", 1);

    const songUri = "spotify:track:" + songId;

    fetch("/api/add-to-playlist", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify([songUri]),
    });
  }

  function handleChange(e) {
    e.preventDefault;
    const formData = e.target.value;

    setSongsToAdd(formData);
  }

  return (
    <>
      <Head>
        <title>Spotify</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Spotify</h1>
        <Row>
          <Col>
            <h2>Daniel&apos;s Top Artists</h2>
            {data.map((artist) => (
              <div key={artist.name}>{artist.name}</div>
            ))}
          </Col>
          <Col>
            <Row>
              <Col xs={12} sm={12} md={12} lg={12}>
                Add
              </Col>
              <Col xs={12} sm={12} md={12} lg={12}>
                <FormControl
                  placeholder='Enter song id'
                  value={songsToAdd}
                  onChange={handleChange}
                />
              </Col>
            </Row>
            <Row className='mt-2'>
              <Col>
                {" "}
                <Button
                  disabled={process.env.NODE_ENV !== "development"}
                  onClick={() => addToPlaylist(songsToAdd)}
                >
                  Add to playlist
                </Button>
              </Col>
            </Row>
          </Col>
        </Row>
      </main>
    </>
  );
}
