import Head from "next/head";
import useSWR from "swr";
import Image from "next/image";
import fetcher from "../lib/fetcher";

export default function Home() {
  const { data, error, isLoading } = useSWR("/api/now-playing", fetcher);

  if (error) return <div>failed to load</div>;
  if (isLoading) return <div>loading...</div>;
  console.log(data);
  return (
    <>
      <Head>
        <title>Spotify</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Spotify</h1>
        Daniel {data.isPlaying ? "is listening to..." : "was listening to..."}
        <div>Artist: {data.artist}</div>
        <div>Song: {data.title}</div>
        <div>Album: {data.album}</div>
        <img src={data.albumImageUrl} width='100' height='100' />
      </main>
    </>
  );
}
